dataset:
  name: CIFAR10
  path: data/cifar10
  batch_size: 128
  num_workers: 4
  n_fixed_batches: 5

model:
  resnet: True        
  use_skip: False     
  num_config: "56"        
  activation: relu  
  dropout: 0     

training:
  epochs: 15
  lr: 0.1
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0005
  device: cuda   
