dataset:
  name: CIFAR10
  path: data/cifar10
  batch_size: 128
  num_workers: 4
  n_fixed_batches: 5

model:
  nn_architecture: "ResNet"       
  num_config: "34"        
  activation: relu  
  dropout: 0.0    

training:
  epochs: 5
  lr: 0.1
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0005
  device: cuda   # if available, else cpu is automatic